### ISSUE TITLE
Will additional CP methods be added ? 

### ISSUE THREAD

**Issue by mat-ej** [joneswack/conformal-predictions-from-scratch#1]
Hi, 

I rly enjoyed your repo, especially the locally weighted conformal regression example. 

I am wondering if you plan on adding additional CP methods in the future for example CQR or I am super interested in ACI, adaptive conformal inference. 

(Example here: https://github.com/ml-stat-Sustech/TorchCP/blob/master/examples/time_series.py)

Thanks and have a great holiday. : )

**Comment by joneswack** [comment]
Hi, thanks for reaching out! I am glad you are enjoying the repo!

I am creating a CQR notebook right now, which should be released soon!
I am also planning to cover time series in the future, but cannot tell you when exactly I will be able to do it :)

Jonas

**Comment by mat-ej** [comment]
Thanks so much, I cant wait to try it.

I dunno why the time series are often omitted from CP repos and literature. (The exchangeability assumption is rarely discussed, i.e. what to do when it does not hold)

**Comment by joneswack** [comment]
Yes that's definitely an important point. In many practical scenarios, the exchangeability assumption is not benign at all, e.g., in time series. So I am very interested in this too!

I just added a CQR notebook!

**Comment by mat-ej** [comment]
thanks so much, just did that tutorial and its very good, straight to the point. (I might try ACI in the same experiment)

Have a great day.

**Comment by joneswack** [comment]
Thanks you too! I'm gonna mark this issue as closed for now, since I have answered your questions.
